- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Delete default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add custom config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/webapp.conf
    owner: root
    group: root
    mode: "0644'
  notify: Reload nginx
  vars:
    nginx_port: 80

- name: Enable site config
  become: yes
  file:
    src: /etc/nginx/sites-available/webapp.conf
    dest: /etc/nginx/sites-enabled/webapp.conf
    state: link
    force: yes
  notify: Reload nginx

- name: Create web root dir
  file:
    path: /opt/static-sites
    state: directory
    owner: webapp
    group: webapp
    mode: '0755'

- name: Deploy index.html template
  template:
    src: index.html.j2
    dest: /opt/static-sites/index.html
    owner: webapp
    group: webapp
    mode: '0644'

- name: Reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Nginx run check
  service:
    name: nginx
    state: started
    enabled: yes
