- name: Create web user
  ansible.builtin.user:
    name: webapp
    shell: /bin/bash
    groups: sudo
    create_home: yes
  become: yes

- name: .ssh file setup
  file:
    path: "/home/webapp/.ssh"
    state: directory
    owner: "webapp"
    group: "webapp"
    mode: '0700'

- name: Generate ssh key
  openssh_keypair:
    path: "/home/webapp/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: webapp
    group: webapp
    mode: '0600'

- name: Add ssh key to auth
  copy:
    src: "/home/webapp/.ssh/id_rsa.pub"
    dest: "/home/webapp/.ssh/authorized_keys"
    owner: webapp
    group: webapp
    mode: '0600'
