- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Ensure fail2ban service is running
  service:
    name: fail2ban
    state: started
    enabled: yes
