- hosts: webservers
  become: yes


  roles:
    - user
    - nginx
    - firewall
    - ssh-hardening
    - security_updates
    - fail2ban

  tasks:
    - name: Debug
      debug:
        var: web_user
    - name: Validate that the HTTP service is running
      uri:
        url: "http://localhost:80/"
        return_content: yes
      register: result

    - name: Page contains string
      assert:
        that:
          - "'Welcome to the website' in result.content"
